### ISSUE TITLE
Collection not triggering any events

### ISSUE THREAD

**Issue by mbajur** [jhudson8/react-backbone#2]
Hello! This lib looks really promissing and i would love to use it to make my code better but i have encountered a blocker at the very beginning of my attempt.

My code is:

### Model

    var CategoryModel = Backbone.Model.extend({
      urlRoot: '/api/v1/categories'
    });

### Collection

    @CategoriesCollection = Backbone.Collection.extend
	  model: CategoryModel
	  url:   '/api/v1/categories'

### React component

    @AddPlaceModal = React.createClass
      mixins: ['collectionEvents']

      getDefaultProps: ->
        categories:   []

      events: {
        'collection': 'collectionChanged'
      }

      collectionChanged: ->
        console.log 'changed'

      # Fetches categories for current menu
      #
      fetchCategories: ->
        categories = new CategoriesCollection
        data       = {f: { place_id_eq: @props.placeId }}
        result     = categories.fetch data: data

        result.success (data) =>
          @props.categories = data

      componentWillMount: ->
        @fetchCategories()

    # ...

And i want to listen for any collection changes (actually, the `reset` event is the most important one right now) but the code above do not triggers any collection events at all. I'm not sure if that's an issue with my code or with react-backbone but if you have any advice or just know what's wrong in here, please let me know.

Thanks!

**Comment by jhudson8** [comment]
How are you referencing the categories collection in your ```AddPlaceModal``` class?  I don't see a render method but, by default, the collection must use the property name of ```collection```.  If you want to change it to be aware of the ```categories``` property, you have to include the ```collectionAware``` mixin with the ```categories``` parameter.

```
mixins: ['collectionAware("categories")', 'collectionEvents']
```

You might get a better understand of things if you looked at the [tutorials](https://github.com/jhudson8/react-backbone/tree/master/tutorials) - and specifically [this one](https://github.com/jhudson8/react-backbone/tree/master/tutorials/collection-binding)

**Comment by mbajur** [comment]
Thanks for your fast reply! Oh, right, my bad, i have somehow missed that section in the tutorial. However, new error has occured:

> the model/collection does not implement on/off functions - you will see problems
> []

And, according to react-backbone source code line which throws it, the mixin can't see my collection. I'm quite sure it something really trivial but i just can't find any example in the tutorial which could help me with that issue. The code there seems to work out of the box while mine is like it's missing something elementary.

Sorry if my questions and issues are dumb, i'm quite fresh react user and some things may not seem  obvious to me.

**Comment by jhudson8** [comment]
No worries,

I specifically put this error message in there to prevent hard to debug issues :)

Basically, the object that you have provided as the collection property to be bound does not expose the necessary methods (on / off / once) to allow react-backbone to listen for appropriate events.

This means that the collection you are providing to the react component is actually not an object that has event support (not an instance of Backbone.Collection).  Try doing a console.log of ```theCollection.on``` - you'll see that it is undefined.

**Comment by mbajur** [comment]
That's exactly what i suspected but i can't see any on/off events defined in your collection object ([example.js](https://github.com/jhudson8/react-backbone/blob/master/tutorials/collection-binding/step7/example.js)) so i've ignored that clue. Is that just for simplicity's sake or i don't know about something?

**Comment by jhudson8** [comment]
Sorry, is what for simplicity's sake?  I don't understand the question.

**Comment by mbajur** [comment]
Are you not defining any on / off methods in your example collection to keep the example short and simple OR all backbone models have such methods by default and if my collection does not have them, it means there is something wrong with it? :)

**Comment by jhudson8** [comment]
The collection in the example has on / off method because it extends ```Backbone.Collection```

https://github.com/jhudson8/react-backbone/blob/master/tutorials/collection-binding/step1/example.js#L12

All of the examples work completely - if you check out the code and run the following commands in the any of the ```step``` directories

```
  npm install
  webpack-dev-server
```

**Comment by mbajur** [comment]
Ok, so that's a default backbone's collection thing - when you're defining a collection object which extends `Backbone.Collection`, it has on/off methods by default. The thing is - i'm also extending Backbone.Collection with my `CategoriesCollection` (code of that collection is posted in this issue body) but react-backbone says that there are no on/off method defined for that collection. And yes, indeed, `CategoriesCollection.on` returns undefined so it seems to be somehow a collection rather than react-backbone related issue.

Anyway - have you any idea why my collection does not have these methods? Our code is practically the same and i feel really confused

**Comment by jhudson8** [comment]
If you are doing something like this, it *will* have on/off/once.  I'd suggest isolating and simplying your code because this is the crux of your problem.  It should look something like this
```
var MyCollectionClass = Backbone.Collection.extend({
  ...
});
var myCollectionInstance = new MyCollectionClass();
console.log(myCollectionInstance);  // this will log "true"
```
Start from there and work your way back to your code.  Are you sure you are passing the collection instance?  Or are you not "newing" it and just using the collection class?

**Comment by mbajur** [comment]
Yes, that was it! :) The issue was pretty lame, i was "listening" for events on `fetch()` result array rather than on collection instance. 

BIG THANKS for all your patience and effort Joe, i really appreciate it.

**Comment by jhudson8** [comment]
no worries, glad you figured it out
