### ISSUE TITLE
Errors on script initialization

### ISSUE THREAD

**Issue by The-Q** [jhudson8/react-backbone#4]
Hello. I'm trying to start working with your library. I'm using your js files without AMD or Require.js and I have multiple errors on page load so everything stops working. 
Here is my setup: 

    <script src="/Scripts/jquery-1.9.1.js"></script>
    <script src="/Scripts/underscore.js"></script>
    <script src="/Scripts/backbone.js"></script>
    <script src="/Scripts/backbone-xhr-events.js"></script>
    <script src="/Scripts/backbone-relational.js"></script>    
    <script src="/Scripts/react/react-0.13.1.js"></script>
    <script src="/Scripts/halogen.js"></script>    
    <script src="/Scripts/react-mixin-manager.js"></script>
    <script src="/Scripts/react-events.js"></script>
    <script src="/Scripts/react-backbone.js"></script>

And when the page loads I get the following error in dev Console
![err](https://cloud.githubusercontent.com/assets/839304/7515963/4a3f423e-f4d4-11e4-97d4-3956e19a14f0.png)

Could you help with this issue? Am I doing something wrong?

**Comment by jhudson8** [comment]
You weren't doing anything wrong... I don't use the scripts in this way (you might want to consider taking a look at [webpack](http://webpack.github.io/) ).  I've fixed the issue (get v1.0.1 of backbone-xhr-events, react-mixin-manager, react-events and react-backbone).

You can see a working example [here](https://dl.dropboxusercontent.com/u/6589453/react-backbone-test/index.html)

**Comment by The-Q** [comment]
Thanks for your work. I'll take a look at updated version. Webpack isn't for me as I'm using Visual Studio.
