### ISSUE TITLE
accessing isMounted inside its render() function

### ISSUE THREAD

**Issue by ecabuk** [jhudson8/react-backbone#5]
Hi,

I am getting a warning like that:

`Warning: SuperFancyReactCompanent is accessing isMounted inside its render() function. render() should be a pure function of props and state. It should never access something that requires stale data from the previous render, such as refs. Move this logic to componentDidMount and componentDidUpdate instead.`

I tried but couldn't figure it out. Is this a bug or am I missing something?

Thanks!

**Comment by jhudson8** [comment]
Yeah as React has progressed it has moved away from the stateful model that this project uses.  I've moved on to using react+redux because backbone just isn't where things are heading with React.
